const $=x=>document.getElementById(x);let nation="Portugal",mission=0,busy=false,S={money:120,trade:12,navy:8,know:10,power:12,human:0},found=new Set(),answered=false;
const H={Lisbon:[23,61],Toledo:[31,61],Barcelona:[42,56],Paris:[37,32],London:[34,21],Venice:[59,44],Constantinople:[87,60],Cairo:[93,82]};
const info={Lisbon:["Portugal","Atlantic port. European merchants want profitable Asian luxuries."],Toledo:["Castile","Royal consumers and elites create demand for expensive imported luxuries."],Barcelona:["Aragon","Mediterranean commercial connections link Iberia to wider markets."],Venice:["Venice","Pepper arriving here has accumulated transport, intermediary, risk and political costs."],Constantinople:["Byzantine → Ottoman","A major crossroads. In 1453 political control changes, but commerce does not simply disappear."],Cairo:["Mamluk Sultanate","Goods from the Indian Ocean pass through Egyptian commercial networks toward Mediterranean consumers."],Paris:["France","Elite European demand helps sustain high prices for imported luxuries."],London:["England","Imported spices and silks are high-status goods in European markets."]};
const views={Iberia:[1.0,0,0],Mediterranean:[.82,-8,-2],Constantinople:[1.18,-34,-10],Regional:[.72,0,0]};
const missions=[
{year:1450,title:"MISSION 1 — THE LUXURY PROBLEM",goal:"Find evidence explaining why Europeans will pay so much for Asian luxuries.",need:["Toledo","Venice","London"],q:"What creates the strongest incentive for merchants to keep importing Asian luxuries?",opts:["European consumers have strong demand for scarce, prestigious imported goods.","Asian goods are free to transport.","European rulers have banned trade.","All European consumers can easily produce silk and pepper."],correct:0,chain:"European recovery → growing wealth → luxury demand → profit opportunity",unlock:"Trade"},
{year:1451,title:"MISSION 2 — FOLLOW THE PEPPER",goal:"Trace the commercial chain and explain why an 8-ducat product can cost over 30 ducats in Europe.",need:["Cairo","Constantinople","Venice"],q:"Which explanation best fits the route evidence?",opts:["Transport, intermediaries, tolls, risk and profit accumulate across the supply chain.","The Ottomans have already ended all trade.","Pepper becomes physically larger on the journey.","Only one merchant controls every market from India to Europe."],correct:0,chain:"Asian pepper → long supply chain → accumulated costs → high European price",unlock:"Explore"},
{year:1452,title:"MISSION 3 — POLITICS CHANGES TRADE",goal:"Investigate how political control and stability can affect commerce without assuming trade simply stops.",need:["Venice","Constantinople","Cairo"],q:"How can political change affect trade?",opts:["It can change risk, tolls, diplomatic access and bargaining power.","Every political change permanently ends commerce.","Politics has no relationship to economics.","It automatically makes all imports cheaper."],correct:0,chain:"Political conditions → risk & costs → supply conditions → market price",unlock:"Diplomacy"},
{year:1453,title:"MISSION 4 — CONSTANTINOPLE",goal:"Test the claim: “The Ottoman conquest closed all European trade with Asia.”",need:["Constantinople","Venice","Cairo"],q:"Which conclusion is better supported?",opts:["Trade continues, but Ottoman control changes political and strategic conditions.","All Asian trade ends permanently in 1453.","Europe immediately controls Indian Ocean trade.","The conquest has no political or economic significance."],correct:0,chain:"Ottoman conquest → political control changes → trade continues/adapts → incentives for alternatives",unlock:"Research"}
];
const homes={Portugal:"Lisbon",Castile:"Toledo",Venice:"Venice",England:"London",France:"Paris"};
function stage(v){let a=views[v]||views.Regional;$("worldstage").style.transform=`translate(${a[1]}%,${a[2]}%) scale(${a[0]})`;$("focusTitle").textContent=`${v} • ${missions[mission]?.year||1453}`}
function line(a,b){let A=H[a],B=H[b],dx=B[0]-A[0],dy=B[1]-A[1],d=document.createElement("div");d.className="route";d.style.left=A[0]+"%";d.style.top=A[1]+"%";d.style.width=Math.hypot(dx,dy)+"%";d.style.transform=`rotate(${Math.atan2(dy,dx)*180/Math.PI}deg)`;$("routes").appendChild(d)}
function draw(){ $("routes").innerHTML="";[["Cairo","Constantinople"],["Constantinople","Venice"],["Venice","Barcelona"],["Barcelona","Lisbon"]].forEach(x=>line(...x));$("hotspots").innerHTML="";Object.entries(H).forEach(([n,p])=>{let b=document.createElement("button");b.className="hotspot";b.style.left=p[0]+"%";b.style.top=p[1]+"%";b.innerHTML=`<span>${n}</span>`;b.onclick=()=>inspect(n);$("hotspots").appendChild(b)})}
function inspect(n){let a=info[n];$("citypanel").classList.remove("hidden");$("citypanel").innerHTML=`<button class="close" id="x">×</button><h3>${n}</h3><b>${a[0]}</b><p>${a[1]}</p><button id="collect">Collect Evidence</button>`;$("x").onclick=()=>$("citypanel").classList.add("hidden");$("collect").onclick=()=>{found.add(n);$("citypanel").classList.add("hidden");renderEvidence();checkReady()}}
function renderEvidence(){let m=missions[mission];$("evidence").innerHTML=m.need.map(n=>`<div class="${found.has(n)?"found":""}"><b>${found.has(n)?"✓ ":"○ "}${n}</b><br>${found.has(n)?info[n][1]:"Investigate this location."}</div>`).join("")}
function checkReady(){let m=missions[mission];if(m.need.every(n=>found.has(n))&&!answered)showQuestion()}
function showQuestion(){let m=missions[mission];$("question").innerHTML=`<div class="question"><b>${m.q}</b>${m.opts.map((o,i)=>`<button data-q="${i}">${o}</button>`).join("")}</div>`;document.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>answer(+b.dataset.q))}
function answer(i){let m=missions[mission];if(i!==m.correct){$("change").innerHTML=`<div class="change"><b>TEST THE EVIDENCE AGAIN.</b><br>That explanation does not account for all three locations. Revisit the evidence and revise your conclusion.</div>`;return}answered=true;chain(m.chain);$("question").innerHTML=`<div class="question success"><b>✓ EVIDENCE SUPPORTS YOUR CONCLUSION</b><br>${m.opts[i]}<br><br><b>${m.unlock} is now unlocked.</b></div>`;$("actions").classList.remove("lockedActions");$("change").innerHTML=`<div class="change"><b>CAUSE → EFFECT</b><br>${m.chain}</div>`}
function chain(s){$("chain").innerHTML=s.split(" → ").map((x,i)=>(i?" → ":"")+`<span class="node">${x}</span>`).join("")}
function missionView(){let m=missions[mission];$("year").textContent=m.year;$("mission").innerHTML=`<div class="missionProgress">MISSION ${mission+1} OF ${missions.length}</div><h2>${m.title}</h2><div class="goal">GOAL: ${m.goal}</div><p class="hint">Click the glowing cities on the locked map, collect the required evidence, then answer the historical question.</p>`;found=new Set();answered=false;$("question").innerHTML="";$("change").innerHTML="";$("actions").classList.add("lockedActions");renderEvidence();stage(mission===0?"Iberia":mission===3?"Constantinople":"Mediterranean");actions()}
function stats(){["money","trade","navy","know","power"].forEach(k=>$(k).textContent=S[k])}
function actions(){let names=["Trade","Explore","Diplomacy","Build","Military","Research"];$("actions").innerHTML=names.map(n=>`<button class="action" data-a="${n}"><b>${n}</b><small>${n===missions[mission].unlock?"Mission decision":"Available after evidence"}</small></button>`).join("");document.querySelectorAll("[data-a]").forEach(b=>b.onclick=()=>decision(b.dataset.a))}
function decision(k){if(!answered)return;let m=missions[mission];let effects={Trade:{money:8,trade:3},Explore:{money:-14,know:5,navy:2},Diplomacy:{money:-6,power:4,trade:2},Build:{money:-16,navy:5},Military:{money:-14,navy:4,power:4,human:3},Research:{money:-10,know:6}}[k],before={...S};Object.entries(effects).forEach(([q,v])=>S[q]+=v);stats();$("change").innerHTML=`<div class="change"><b>YOUR DECISION — ${k}</b><br>${Object.keys(effects).map(q=>`${q}: ${before[q]} → ${S[q]}`).join(" • ")}<br><b>Historical reasoning:</b> ${m.chain}</div>`;setTimeout(()=>{if(mission<missions.length-1){mission++;missionView()}else finish()},900)}
function finish(){$("mission").innerHTML=`<h2>PROTOTYPE 1.1 COMPLETE</h2><p>You investigated demand, supply-chain costs, politics and the 1453 conquest before making strategic choices.</p><p><b>Explain:</b> How can demand for Asian goods eventually create incentives for maritime exploration?</p>`;$("actions").classList.add("lockedActions");$("question").innerHTML=`<div class="question"><a href="lesson.html">Open exit ticket and lesson summary →</a></div>`}
$("nations").innerHTML=Object.keys(homes).map(n=>`<button class="nation ${n===nation?"active":""}" data-n="${n}">${n}<small>Campaign perspective</small></button>`).join("");document.querySelectorAll("[data-n]").forEach(b=>b.onclick=()=>{nation=b.dataset.n;document.querySelectorAll(".nation").forEach(x=>x.classList.toggle("active",x===b));stage(nation==="Portugal"||nation==="Castile"?"Iberia":"Mediterranean")});$("home").onclick=()=>stage(nation==="Portugal"||nation==="Castile"?"Iberia":"Mediterranean");$("regional").onclick=()=>stage("Regional");$("eventFocus").onclick=()=>stage(mission===3?"Constantinople":"Mediterranean");draw();stats();chain("European recovery → luxury demand → costly Asian trade");missionView();