const $=x=>document.getElementById(x),NS='http://www.w3.org/2000/svg';let m=0,found=new Set(),answered=false,book=[],S={money:120,trade:12,navy:8,know:10,power:12,human:0};
const C={Lisbon:[165,165],Toledo:[205,170],Barcelona:[260,170],London:[210,110],Paris:[245,130],Venice:[335,165],Constantinople:[470,205],Cairo:[465,285],Calicut:[690,340],Malacca:[835,365],Canton:[885,255],Zanzibar:[555,405]};
const I={Toledo:['Castile','Elite demand sustains a market for imported luxuries.'],London:['England','Spices and silks are scarce, prestigious imports.'],Venice:['Venice','European pepper price in this teaching model: 31 ducats.'],Calicut:['Malabar Coast','Pepper source-market teaching price: 8 ducats; Indian Ocean commerce predates Portuguese arrival.'],Cairo:['Mamluk Sultanate','Pepper teaching model: 8 → 17 after shipping, merchants and duties.'],Constantinople:['Byzantine → Ottoman','Teaching model: 17 → 24 after transport, risk and merchant profit.'],Lisbon:['Portugal','Atlantic port and Portuguese campaign home.'],Barcelona:['Aragon','Mediterranean-facing commercial center.'],Paris:['France','Court demand supports luxury imports.'],Malacca:['Malacca Sultanate','Major Southeast Asian entrepôt.'],Canton:['Ming China','Regulated Chinese market for silk and porcelain.'],Zanzibar:['Swahili Coast','Part of long-established Indian Ocean networks.']};
const M=[
[1450,'THE LUXURY PROBLEM','Find evidence explaining why Asian luxuries create profit opportunities in Europe.',['Toledo','London','Venice'],'Why do merchants keep importing costly Asian luxuries?',['Strong demand for scarce, prestigious imports creates profit opportunities.','Transport is free.','European rulers ban Asian goods.','Pepper grows everywhere in Europe.'],0,'wealth & recovery → luxury demand → scarcity → high willingness to pay → profit opportunity','Trade'],
[1451,'FOLLOW THE PEPPER','Trace pepper and account for its rising price.',['Calicut','Cairo','Constantinople','Venice'],'Why does the price rise along the route?',['Transport, intermediaries, duties, risk and profit accumulate.','Pepper physically grows.','One ruler sets every price.','Trade has stopped.'],0,'Calicut 8 → Cairo 17 → Constantinople 24 → Venice 31 → incentive for cheaper access','Explore'],
[1452,'POLITICS CHANGES TRADE','Determine how politics changes commercial conditions.',['Cairo','Constantinople','Venice'],'What is best supported?',['Political control can alter risk, tolls, diplomacy and bargaining power without automatically ending trade.','Every political change ends trade.','Politics never affects prices.','War always makes imports cheaper.'],0,'political conditions → risk/tolls/access → supply costs → market prices','Diplomacy'],
[1453,'CONSTANTINOPLE: TEST THE CLAIM','Evaluate: “The Ottoman conquest closed all European trade with Asia.”',['Constantinople','Cairo','Venice'],'What does the evidence support?',['Trade continues and adapts while Ottoman control changes strategic conditions.','All trade ends in 1453.','Europe instantly controls India.','Nothing changes.'],0,'Ottoman conquest → political control changes → trade adapts/continues → incentives for alternatives','Research']];
function route(a,b){let A=C[a],B=C[b],l=document.createElementNS(NS,'line');['x1','y1','x2','y2'].forEach((k,i)=>l.setAttribute(k,[A[0],A[1],B[0],B[1]][i]));l.setAttribute('class','svgroute');$('svgRoutes').appendChild(l)}

const REALMS=[["PORTUGAL","#47768d",[[140,145],[180,145],[180,195],[145,195]]],["CASTILE","#a35f50",[[180,145],[235,145],[235,195],[180,195]]],["ARAGON","#b8924b",[[235,150],[280,150],[280,190],[235,190]]],["FRANCE","#58729a",[[215,105],[290,105],[290,150],[215,150]]],["ENGLAND","#7d4d4d",[[185,75],[240,75],[240,115],[185,115]]],["HOLY ROMAN EMPIRE","#88764f",[[290,105],[390,105],[390,170],[290,170]]],["VENICE","#4f8a78",[[320,150],[355,150],[355,180],[320,180]]],["OTTOMAN EMPIRE","#708b4f",[[430,170],[520,170],[520,245],[430,245]]],["MAMLUK SULTANATE","#ae894d",[[420,245],[515,245],[515,335],[420,335]]]];
function drawRealmArt(){let g=$("realmArt");g.innerHTML="";REALMS.forEach(([n,c,p])=>{let q=document.createElementNS(NS,"polygon");q.setAttribute("points",p.map(x=>x.join(",")).join(" "));q.setAttribute("fill",c);q.setAttribute("class","realmArt");g.appendChild(q);let t=document.createElementNS(NS,"text"),cx=p.reduce((s,x)=>s+x[0],0)/p.length,cy=p.reduce((s,x)=>s+x[1],0)/p.length;t.setAttribute("x",cx);t.setAttribute("y",cy);t.setAttribute("text-anchor","middle");t.setAttribute("class","realmName");t.textContent=n;g.appendChild(t)})}
const VIEWS={Europe:"0 50 560 330",Mediterranean:"220 120 430 300",IndianOcean:"400 170 570 360"};
function setView(v){$("svgmap").setAttribute("viewBox",VIEWS[v]);document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===v))}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>setView(b.dataset.view));

function draw(){drawRealmArt(); $('svgRoutes').innerHTML='';[['Canton','Malacca'],['Malacca','Calicut'],['Calicut','Cairo'],['Calicut','Zanzibar'],['Cairo','Constantinople'],['Constantinople','Venice'],['Venice','Barcelona'],['Barcelona','Lisbon']].forEach(x=>route(...x));$('svgCities').innerHTML='';Object.entries(C).forEach(([n,p])=>{let c=document.createElementNS(NS,'circle');c.setAttribute('cx',p[0]);c.setAttribute('cy',p[1]);c.setAttribute('r',7);c.setAttribute('class','svgcity '+(M[m][3].includes(n)?'need':''));c.onclick=()=>inspect(n);$('svgCities').appendChild(c);let t=document.createElementNS(NS,'text');t.setAttribute('x',p[0]+9);t.setAttribute('y',p[1]-7);t.setAttribute('class','svglabel');t.textContent=n;$('svgCities').appendChild(t)})}
function inspect(n){let d=I[n]||['Historical location','Context develops in later missions.'];$('citypanel').classList.remove('hidden');$('citypanel').innerHTML=`<button id="cx">×</button><h3>${n}</h3><b>${d[0]}</b><p>${d[1]}</p><button id="collect">Add to Evidence Book</button>`;$('cx').onclick=()=>$('citypanel').classList.add('hidden');$('collect').onclick=()=>collect(n,d)}
function collect(n,d){found.add(n);if(!book.some(x=>x.n===n&&x.m===m))book.push({n,m,text:d[1]});$('citypanel').classList.add('hidden');renderBook();renderEvidence();if(M[m][3].every(x=>found.has(x)))question()}
function renderBook(){$('book').innerHTML=book.length?book.map(x=>`<div class="bookCard"><b>${x.n}</b><br>${x.text}</div>`).join(''):'<small>No evidence collected yet.</small>'}
function renderEvidence(){$('evidence').innerHTML=M[m][3].map(n=>`<div class="ecard ${found.has(n)?'found':''}"><b>${found.has(n)?'✓':'○'} ${n}</b><br>${found.has(n)?I[n][1]:'Investigate on map.'}</div>`).join('')}
function question(){$('question').innerHTML=`<div class="question"><b>${M[m][4]}</b>${M[m][5].map((o,i)=>`<button data-q="${i}">${o}</button>`).join('')}</div>`;document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>answer(+b.dataset.q))}
function answer(i){if(i!==M[m][6]){$('change').innerHTML='<div class="change"><b>REVISE YOUR CLAIM.</b> Recheck the evidence; this explanation does not account for all locations.</div>';return}answered=true;chain(M[m][7]);$('question').innerHTML=`<div class="question success"><b>✓ CLAIM SUPPORTED BY EVIDENCE</b><br>${M[m][5][i]}<br><b>${M[m][8]} unlocked.</b></div>`;$('actions').classList.remove('locked')}
function chain(s){$('chain').innerHTML=s.split(' → ').map((x,i)=>(i?' → ':'')+`<span class="node">${x}</span>`).join('')}
function mission(){let q=M[m];$('year').textContent=q[0];$('mission').innerHTML=`<h2>MISSION ${m+1}: ${q[1]}</h2><div class="goal">GOAL: ${q[2]}</div><p>Click highlighted cities, add evidence to your Evidence Book, then make a claim.</p>`;found=new Set();answered=false;$('question').innerHTML='';$('change').innerHTML='';$('actions').classList.add('locked');renderEvidence();draw();setView(m===0?"Europe":m===1?"IndianOcean":"Mediterranean");actions()}
function actions(){let names=['Trade','Explore','Diplomacy','Build','Military','Research'];$('actions').innerHTML=names.map(n=>`<button class="action" data-a="${n}"><b>${n}</b><small>${n===M[m][8]?'Mission decision':'Strategic option'}</small></button>`).join('');document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>decision(b.dataset.a))}
function decision(k){if(!answered)return;let d={Trade:{money:8,trade:3},Explore:{money:-14,know:5,navy:2},Diplomacy:{money:-6,power:4,trade:2},Build:{money:-16,navy:5},Military:{money:-14,navy:4,power:4,human:3},Research:{money:-10,know:6}}[k],before={...S};Object.entries(d).forEach(([q,v])=>S[q]+=v);stats();$('change').innerHTML=`<div class="change"><b>YOUR DECISION — ${k}</b><br>${Object.keys(d).map(q=>q+': '+before[q]+' → '+S[q]).join(' • ')}<br><b>Reasoning:</b> ${M[m][7]}</div>`;setTimeout(()=>{if(m<M.length-1){m++;mission()}else finish()},900)}
function stats(){['money','trade','navy','know','power'].forEach(k=>$(k).textContent=S[k])}
function finish(){$('mission').innerHTML='<h2>PROTOTYPE 1.2 COMPLETE</h2><p>Use your Evidence Book: explain how luxury demand, supply-chain costs and political conditions could encourage maritime exploration.</p>';$('actions').classList.add('locked')}
$('nations').innerHTML=['Portugal','Castile','Venice','England','France'].map(n=>`<button class="nation">${n}</button>`).join('');$('event').innerHTML='<b>INQUIRY CAMPAIGN</b><p>Evidence first. Decisions unlock only after students support a historical claim.</p>';renderBook();stats();chain('European recovery → luxury demand → costly Asian trade');mission();