const $=x=>document.getElementById(x);let y=1450,nation="Portugal",lastFocus="Portugal",S={money:120,trade:12,navy:8,know:10,power:12,human:0};
const focus={Portugal:[1.18,-10,-5],Castile:[1.22,-22,-6],Venice:[1.18,-34,-5],England:[1.16,-20,2],France:[1.18,-25,-2],Constantinople:[1.35,-48,-10],Mediterranean:[1.0,-20,-8],Cape:[.82,4,-3],Calicut:[.72,-5,-2],Malacca:[.65,-2,-2],Canton:[.62,0,-2]};
const events={1453:["CONSTANTINOPLE FALLS","Mehmed II captures Constantinople. Byzantine rule ends; commerce continues under a changed political environment.","Constantinople","Ottoman conquest → political control changes → trade adapts → strategic pressure"],1469:["ISABELLA MARRIES FERDINAND","Castile and Aragon enter a dynastic partnership while retaining distinct institutions.","Castile","Dynastic marriage → cooperation → stronger Iberian coordination"],1488:["DIAS ROUNDS THE CAPE","Bartolomeu Dias rounds southern Africa.","Cape","Navigation investment → Cape rounded → route knowledge"],1492:["GRANADA FALLS • COLUMBUS CROSSES ATLANTIC","Granada falls. Columbus reaches Caribbean islands inhabited by Indigenous peoples while seeking Asia.","Castile","Iberian competition → westward gamble → Caribbean encounter → colonization"],1498:["DA GAMA REACHES CALICUT","Portugal reaches Calicut and enters an existing Indian Ocean commercial system.","Calicut","Cape route → Calicut → existing markets → competition for access"],1511:["PORTUGAL CAPTURES MALACCA","Portugal seizes Malacca; regional trade adapts.","Malacca","Trade competition → armed seizure → port control → imperial power"],1517:["PORTUGUESE CONTACT WITH MING CHINA","Portuguese merchants enter the Ming commercial sphere under Chinese regulation.","Canton","Maritime expansion → Chinese market contact → regulated access"]};
const homes={Portugal:"Portugal",Castile:"Castile",Venice:"Venice",England:"England",France:"France"};
function camera(k){lastFocus=k;let a=focus[k]||focus.Mediterranean;$("mapimg").style.transform=`scale(${a[0]})`;$("mapimg").style.left=a[1]+"%";$("mapimg").style.top=a[2]+"%";$("focusTitle").textContent=`${k} • ${y}`}
function chain(s){$("chain").innerHTML=s.split(" → ").map((x,i)=>(i?" → ":"")+`<span class="node">${x}</span>`).join("")}chain("European recovery → luxury demand → costly Asian trade");
function stats(){["money","trade","navy","know","power"].forEach(k=>$(k).textContent=S[k]);$("year").textContent=y}
function log(s){$("log").innerHTML=`<div><b>${y}</b> ${s}</div>`+$("log").innerHTML}
function event(){let e=events[y];if(e){$("event").innerHTML=`<b>HISTORICAL RECORD • ${y}</b><h2>${e[0]}</h2><p>${e[1]}</p><a href="sources.html#y${y}">Source trail →</a>`;chain(e[3]);camera(e[2])}else $("event").innerHTML=`<b>WORLD TURN • ${y}</b><h2>Your court must decide.</h2><p>The map stays focused on the geography relevant to your choice.</p>`}
const L={Trade:["Asian demand → established routes → costs accumulate → European prices rise → profit incentive",{money:8,trade:3},"Trade","Mediterranean"],Explore:["Costly trade → search for alternatives → voyages → route knowledge → new access",{money:-14,know:5,navy:2},"Explore",null],Diplomacy:["Political power → negotiation → access → lower friction",{money:-6,power:4,trade:2},"Diplomacy","Venice"],Build:["Investment → ships and ports → capacity → long-range trade",{money:-16,navy:5},"Build",null],Military:["Commercial rivalry → force → route control → imperial power → human cost",{money:-14,navy:4,power:4,human:3},"Military","Mediterranean"],Research:["Investment → knowledge → lower uncertainty → longer voyages",{money:-10,know:6},"Research",null]};
function actions(){$("actions").innerHTML=Object.entries(L).map(([k,v])=>`<button class="action" data-a="${k}"><b>${k}</b><small>${v[0].split(" → ")[0]}…</small></button>`).join("");document.querySelectorAll("[data-a]").forEach(b=>b.onclick=()=>choose(b.dataset.a))}
function choose(k){let before={...S},d=L[k][1];Object.entries(d).forEach(([q,v])=>S[q]+=v);chain(L[k][0]);let f=L[k][3]||(k==="Explore"?(y>=1488?"Cape":homes[nation]):homes[nation]);camera(f);$("change").innerHTML=`<div class="change"><b>YOUR DECISION — ${k}</b><br>${Object.keys(d).map(q=>`${q}: ${before[q]} → ${S[q]}`).join(" • ")}<br><b>CAUSE:</b> ${L[k][0]}</div>`;log(`<span style="color:#e99a6d">STUDENT COUNTERFACTUAL</span> — ${nation}: ${k}`);y++;render()}
function render(){stats();event();actions()}
$("nations").innerHTML=Object.keys(homes).map(n=>`<button class="nation ${n===nation?"active":""}" data-n="${n}">${n}<small>Focused campaign view</small></button>`).join("");document.querySelectorAll("[data-n]").forEach(b=>b.onclick=()=>{nation=b.dataset.n;document.querySelectorAll(".nation").forEach(x=>x.classList.toggle("active",x===b));camera(homes[nation])});
$("home").onclick=()=>camera(homes[nation]);$("regional").onclick=()=>camera("Mediterranean");$("eventFocus").onclick=()=>camera(lastFocus);camera("Portugal");render();